### ISSUE TITLE
Benchmark NTL vs flint

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#119]
Compare the performance of NTL vs Flint for the following field moduli:

- BLS12-381: 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001

_note to clarify: this is the order of a subgroup in BLS12-381 --- distinct from the order or base field of BLS12-381_

for the following operations:
- power sum solver
- polynomial interpolation
- computing power sums

**Comment by amiller** [comment]
- berlekamp-welch decoding

We should identify at what value of N it matters whether we have FFT available or not. It could be that this rarely matters.

Moduli:
- 2^32  for if we do not use polycommitments at all
- alt_bn128 order (probably not much different): 21888242871839275222246405745257275088548364400416034343698204186575808495617

**Comment by rahulgovind** [comment]
Polynomial multiplication is an expensive part of batch reconstruction. So based on these [reports](https://www.shoup.net/ntl/benchmarks.pdf), I would guess that NTL is better for hbmpc (Consider `k=1/4` in the reports or `#bits in p = 256`). Unfortunately, the report does not include any details for very small n (`n < 256`) so I'm just going by the numbers for `n = 256`.  Actually, non-FFT methods might be faster for small n.

Since BLS12-381 has a large 2^r root of unity, FFT will be available for a sufficiently large n. So I don't think that's an issue. 

Regarding the Berlemap-Welch algorithm, the decoding in batch reconstruction currently has a worst-case time complexity of `O(N^4)`. Every failed Berlekamp-Welch run (too many errors) takes O(N^3) time. If `t` errors are present, we would have `t-1` failures, one for each time we try decoding with `2t+1` shares, `2t+2` shares, ..., `3t` shares (with `n=3t+1`). Error-decoding only after all`n` shares have been received would improve the worst-case to `O(N^3)`.

**Comment by smkuls** [comment]
Can we implement just the lagrange interpolation (it shouldn't be too much code) in both NTL and Flint and compare the performance numbers?

There's no need to call them from Python - simple C++ implementation should suffice. If you are on a time crunch - you can pick one over the other and stitch it in with the python version for now.

However, for this issue lets compare actual implementations for our specific use cases.

**Comment by amiller** [comment]
We can close this issue, I think the decision made in #160 #152 to use NTL is fine, and we can focus on just benchmarking for example FFT vs Vandermonde operation
