### ISSUE TITLE
Import bindings to a Rust library providing BLS12-381

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#13]
We're planning on using BLS12-381 for our cryptography and JubJub for elliptic curve cryptography applications within the MPC. The PBC library we're already using does not support BLS12-381, and we don't know of any efficient python libraries. Relic supports it but has bad bindings. We will prefer to use rust for modules, so we're going to try port all of the rust libraries, but just build our own rust module that uses it.

**Comment by amiller** [comment]
Rahul made an initial version of this here, https://github.com/hybridNeo/pairing as a fork of `pairing`. This is cool, making a python wrapper could be something that the `pairing` merges upstream.

**Comment by amiller** [comment]
- [x] convert to python3
- [x] install this as a dependency in the hbmpc docker environment

**Comment by sbellem** [comment]
> install this as a dependency in the hbmpc docker environment

If we keep the Alpine linux image this is non-trivial. See a possible approach at https://github.com/sbellem/pairing/blob/docker-build/wheel.Dockerfile (instructions are at https://github.com/sbellem/pairing/blob/docker-build/RustBindings.md#python-wheel).

The simplest and easiest approach for now will probably be to switch to a glibc friendly image such as ubuntu, as opposed to a musl lib one like Alpine.

### Notes
1. PyO3 minimum required rust version is 1.30.0-nightly 2018-08-18
2. it is not possible to install the nightly build on Alpine linux which is what we use for the HBMPC Dockerfile
3. workaround 1: we could change the HBMPC docker image from Alpine (musl) to Ubuntu (glibc)
4. workaround 2: we could build binaries (python wheel) but installing a wheel on Alpine linux requires a workaround as well (ref: https://github.com/pypa/pip/issues/3969#issuecomment-247381915)

The workaround in point 4 was chosen for now (see https://github.com/sbellem/HoneyBadgerMPC/blob/rust-zkcrypto-pairing/Dockerfile) in order to avoid changing the base image of HBMPC. Running the example @hybridNeo gave works. If we encounter weird problem we can always try the other workaround which involves changing HBMPC's base image to a glibc friendly linux distro such as Ubuntu or CentOS.

#### Relevant links
* https://github.com/pypa/pip/issues/3969
* https://github.com/pypa/manylinux/issues/37
* https://github.com/docker-library/docs/issues/904

**Comment by amiller** [comment]
This is completed by @tyurek  with #201 #196 #238 etc
